apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application

dependencies:
  - name: postgresql
    version: 11.6.18
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

version: 0.3.6

appVersion: "0.1.0"

