{
 "title": "MyApp",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gin_request_duration_bucket{service=\"myapp\",uri!=\"\",uri!=\"/health\"}[1m])) by (uri,le))",
     "legendFormat": "0.99 {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gin_request_duration_bucket{service=\"myapp\",uri!=\"\",uri!=\"/health\"}[1m])) by (uri,le))",
     "legendFormat": "0.95 {{uri}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(gin_request_duration_bucket{service=\"myapp\",uri!=\"\",uri!=\"/health\"}[1m])) by (uri,le))",
     "legendFormat": "0.5 {{uri}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gin_uri_request_total{uri!=\"/health\",uri!=\"\"}[1m]))by(method,uri)",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(gin_uri_request_total{code=\"500\"}[1m])) by (method, code, uri)",
     "legendFormat": "{{code}} {{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Ingress Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by(le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by(le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{}[1m])) by(le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Ingress RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{}[1m])) by(method,host)",
     "legendFormat": "{{method}} {{host}}"
    }
   ]
  },
  {
   "title": "Ingress Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=\"500\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "POD CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"myapp.*\"}[2m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "POD Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{pod=~\"myapp.*\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DB sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{}[2m])) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}