apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "app.fullname" . }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "app.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "app.fullname" . }}
  apiGroup: rbac.authorization.k8s.io