apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
data:
  PG_ADDR: "{{ include "postgresql.fullname" .}}:5432"
  PG_USR: {{ .Values.global.postgresql.auth.username }}
  PG_DBNAME: {{ .Values.global.postgresql.auth.database }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
type: Opaque
data:
  PG_PWD: {{ .Values.global.postgresql.auth.password | b64enc | quote }}